In [1]:
import pandas as pd 
import numpy as np
from tqdm import tqdm
pd.options.display.max_columns = None
pd.options.display.max_rows = 200
pd.options.mode.chained_assignment = None  # default='warn'


num_games = 10

In [2]:
season_2020 = pd.read_csv('data/Season(2019-20).csv')
season_2019 = pd.read_csv('data/Season(2018-19).csv')
roto_2020 = pd.read_csv('data/RotoGuru(19-20).csv', delimiter = ':')
roto_2019 = pd.read_csv('data/RotoGuru(18-19).csv', delimiter = ':')


print(season_2020.shape, season_2019.shape)
print(roto_2020.shape, roto_2019.shape)
season_2020.head(1)

(22975, 27) (30847, 27)
(32008, 37) (42862, 37)

,Date,GameID,Name,Team,OPP,Home,Away,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+-
0,20191022,20191022-Nor-Tor,Jrue Holiday,Nor,Tor,1,0,41.05,6,15,0.4,1,6,0.167,0,2,0.0,2,2,4,6,0,2,5,2,13,-14

In [3]:
roto_2020.head(1)

,GID,"Last, First",First Last,Date,Team,Opp,H/A,GameID,GTime(ET),Team pts,Opp pts,Start,Minutes,GP,active,FDP,DKP,DDP,YHP,Stats,DoubleD,TripleD,FD Sal,FD Change,DK Sal,DK Change,DD Sal,DD Change,YH Sal,YH Change,FD pos,DK pos,DD pos,YH pos,ADI,VMI,Unnamed: 36
0,5679,"Eubanks, Drew",Drew Eubanks,20200308,sas,cle,A,20200308-sas-cle,19.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3500.0,0.0,3000.0,0.0,NaN,NaN,10.0,0.0,5.0,5.0,NaN,5.0,*,*,NaN

### Merging Fantasy and Roto

In [4]:
def organize_roto(r_df): 
    r_df = r_df[['GameID', 'First  Last', 'Date', 'Team','FDP', 'FD Sal', 'FD Change', 'FD pos']]
    r_df['Name'] = np.array(r_df['First  Last'])
    r_df['FDS'] = np.array(r_df['FD Sal'])
    r_df['FD_change'] = np.array(r_df['FD Change'])
    r_df['FD_pos'] = np.array(r_df['FD pos'])
    new_df = r_df.drop(['First  Last', 'FD Sal', 'FD Change', 'FD pos'], axis =1)[['GameID', 'Name','Date', 'Team','FDP', 'FDS', 'FD_change', 'FD_pos']]
    return new_df

def organize_stat(stat_df): 
    new_df = stat_df
    new_df['Team'] = new_df.Team.map(lambda x: x.lower())
    new_df['OPP'] = new_df.OPP.map(lambda x: x.lower())
    new_df['GameID'] = new_df.GameID.map(lambda x: x.lower())
    return new_df
def merge_tables(stat_df, roto_df, season):
    '''This function will merge the dataframes'''
    roto_df = organize_roto(roto_df)
    stat_df = organize_stat(stat_df)
    merge_df = pd.merge(roto_df, stat_df, on = ['GameID', 'Name', 'Team', 'Date'], how = 'inner')
    merge_df = merge_df.sort_values(by = ['GameID', 'Team'])    
    merge_df.to_csv(f'NewData/Merge({season})[{num_games}].csv', index = False)
    return merge_df
merge_2020 = merge_tables(season_2020, roto_2020, '19-20')
merge_2019 = merge_tables(season_2019, roto_2019, '18-19')

In [5]:
merge_2020.shape, merge_2019.shape

((20378, 31), (27826, 31))

In [6]:
merge_2020.head()

,GameID,Name,Date,Team,FDP,FDS,FD_change,FD_pos,OPP,Home,Away,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+-
2064,20191022-lal-lac,Terance Mann,20191022,lac,0.0,3500.0,NaN,2.0,lal,0,1,0.00,0,0,0.0,0,0,0.0,0,0,0.0,0,0,0,0,0,0,0,0,0,0
2274,20191022-lal-lac,Patrick Patterson,20191022,lac,7.6,3500.0,NaN,4.0,lal,0,1,5.17,0,1,0.0,0,1,0.0,0,0,0.0,0,0,0,0,0,0,0,1,0,-5
5124,20191022-lal-lac,Montrezl Harrell,20191022,lac,34.4,7300.0,NaN,5.0,lal,0,1,8.30,2,5,0.4,0,0,0.0,0,0,0.0,1,1,2,0,0,0,1,2,4,6
5627,20191022-lal-lac,Patrick Beverley,20191022,lac,24.0,5100.0,NaN,1.0,lal,0,1,9.40,0,2,0.0,0,2,0.0,0,0,0.0,1,3,4,0,0,0,1,1,0,-5
7221,20191022-lal-lac,Landry Shamet,20191022,lac,14.6,4200.0,NaN,1.0,lal,0,1,5.50,0,1,0.0,0,1,0.0,0,0,0.0,0,1,1,0,0,0,0,0,0,-7

In [7]:
def get_averages(df, season): 
    col = ['MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
                  '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
                  'TOV', 'PF', 'PTS', '+-', 'FDP','FDS']
    add_col = [f'{num_games}_{i}' for i in col]
    new_df = pd.DataFrame(columns = add_col)
    player_list = np.array(df.Name.value_counts().index)
    for player in tqdm(player_list):
        player_df = df[df.Name == player]
        player_df = player_df.sort_values(by = 'Date')
        for c in col: 
            avg = []
            for row in range(len(player_df)):
                if row < num_games: 
                    avg.append(0)
                    continue 
                last = player_df.iloc[row-num_games:row][f'{c}'].mean()
                avg.append(last)
            player_df[f'{num_games}_{c}'] = avg
        new_df = new_df.append(player_df,ignore_index = True)
        
    new_df = new_df[[i for i in new_df.columns.to_list() if i not in add_col] + [i for i in new_df.columns.to_list() if i in add_col]]    
    new_df.sort_values(by = ['GameID', 'Team'], inplace = True)
    new_df.to_csv(f'NewData/AVG({season})[{num_games}].csv')
    return new_df


get_averages(merge_2020, season = '19-20')
get_averages(merge_2019, season = '18-29')

100%|██████████| 471/471 [05:17<00:00,  1.48it/s]
100%|██████████| 488/488 [07:35<00:00,  1.07it/s]

,GameID,Name,Date,Team,FDP,FDS,FD_change,FD_pos,OPP,Home,Away,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,+-,10_MP,10_FG,10_FGA,10_FG%,10_3P,10_3PA,10_3P%,10_FT,10_FTA,10_FT%,10_ORB,10_DRB,10_TRB,10_AST,10_STL,10_BLK,10_TOV,10_PF,10_PTS,10_+-,10_FDP,10_FDS
312,20181016-okc-gsw,Kevon Looney,20181016.0,gsw,33.0,3500.0,NaN,4.0,okc,0.0,1.0,6.41,1.0,3.0,0.333,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,3.0,0.000,0.0,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
414,20181016-okc-gsw,Klay Thompson,20181016.0,gsw,16.8,6800.0,NaN,2.0,okc,0.0,1.0,7.26,1.0,2.0,0.500,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,4.0,0.000,0.0,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
2112,20181016-okc-gsw,Stephen Curry,20181016.0,gsw,55.1,9600.0,NaN,1.0,okc,0.0,1.0,9.37,4.0,5.0,0.800,2.0,2.0,1.0,2.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,2.0,12.0,10.0,0.000,0.0,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
2293,20181016-okc-gsw,Andre Iguodala,20181016.0,gsw,7.4,4300.0,NaN,2.0,okc,0.0,1.0,4.34,1.0,1.0,1.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,2.0,4.0,0.000,0.0,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
2383,20181016-okc-gsw,Kevin Durant,20181016.0,gsw,48.6,10600.0,NaN,3.0,okc,0.0,1.0,12.00,4.0,8.0,0.500,0.0,2.0,0.0,2.0,2.0,1.0,0.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,10.0,8.0,0.000,0.0,0.0,0.0000,0.0,0.0,0.000,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7520,20190613-tor-gsw,Norman Powell,20190613.0,tor,0.2,NaN,NaN,NaN,gsw,1.0,0.0,10.50,0.0,2.0,0.000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,5.0,9.044,1.2,2.7,0.2353,0.6,1.4,0.225,0.5,0.9,0.20,0.0,1.4,1.4,0.4,0.1,0.0,0.2,0.8,3.5,-0.5,10.94,3800.0
16785,20190613-tor-gsw,OG Anunoby,20190613.0,tor,0.0,NaN,NaN,NaN,gsw,1.0,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.858,0.6,1.5,0.1917,0.2,0.8,0.150,0.2,0.2,0.10,0.2,0.5,0.7,0.4,0.2,0.0,0.5,0.4,1.6,0.0,6.42,3850.0
25447,20190613-tor-gsw,Patrick McCaw,20190613.0,tor,0.0,NaN,NaN,NaN,gsw,1.0,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.084,0.0,0.1,0.0000,0.0,0.0,0.000,0.0,0.0,0.00,0.1,0.0,0.1,0.3,0.1,0.0,0.0,0.3,0.0,-0.8,0.87,3500.0
26330,20190613-tor-gsw,Malcolm Miller,20190613.0,tor,0.0,NaN,NaN,NaN,gsw,1.0,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.862,0.2,0.3,0.0667,0.1,0.2,0.050,0.3,0.4,0.15,0.0,0.2,0.2,0.1,0.0,0.1,0.0,0.1,0.8,1.1,1.49,3500.0
26742,20190613-tor-gsw,Jodie Meeks,20190613.0,tor,0.0,NaN,NaN,NaN,gsw,1.0,0.0,0.00,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.868,0.2,0.5,0.0400,0.1,0.2,0.050,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.1,0.0,0.1,0.1,0.5,0.1,0.70,3500.0

In [ ]:
def last_five(df, season): 
    player_list = np.array(df.Name.value_counts().index) 
    new_df = pd.DataFrame(columns = df.columns.to_list()+['LastFive'])
    for player in tqdm(player_list):
        player_df = df[df.Name == player]
        player_df = player_df.sort_values(by = 'Date')
        averages = [] 
        for row in range(len(player_df)): 
            if row < num_games: 
                averages.append(None)
                continue
            last = player_df.iloc[row-num_games:row, :]['+-'].mean()
            averages.append(last)
        player_df['Last'] = averages
        new_df = new_df.append(player_df, ignore_index = True)
    new_df['Team'] = new_df.Team.map(lambda x: x.lower())
    new_df['OPP'] = new_df.OPP.map(lambda x: x.lower())
    new_df['GameID'] = new_df.GameID.map(lambda x: x.lower())
    new_df.to_csv(f'NewData/Season({season})[{num_games}].csv', index = False)
    return new_df.sort_values(by = ['GameID', 'Team'])

In [ ]:
season_2020 = last_five(season_2020, season = '19-20')
season_2019 = last_five(season_2019, season = '18-19')

## Merging Fantasy and Stats FanDuel

In [ ]:
def organize_roto(roto_df): 
    roto_df = roto_df[['GameID', 'First  Last', 'Date', 'Team','FDP', 'FD Sal', 'FD Change', 'FD pos']]
    roto_df['Name'] = np.array(roto_df['First  Last'])
    roto_df = roto_df.drop(['First  Last'], axis =1)[['GameID', 'Name','Date', 'Team','FDP', 'FD Sal', 'FD Change', 'FD pos']]
    print(roto_df.shape)
    return roto_df

In [ ]:
roto_2020 = pd.read_csv('data/RotoGuru(19-20).csv', delimiter = ':')
roto_2019 = pd.read_csv('data/RotoGuru(18-19).csv', delimiter = ':')

roto_2020 = organize_roto(roto_2020)
roto_2019 = organize_roto(roto_2019)

In [ ]:
season_2020 = pd.read_csv(f'NewData/Season(19-20)[{num_games}].csv')
season_2019 = pd.read_csv(f'NewData/season(18-19)[{num_games}].csv')
print(season_2020.shape, season_2019.shape)

In [ ]:
def flast_five(stat_df, roto_df, season):
    '''This function takes the stat df and fantasy df for a single season and combines them.  It will return a combined dataframe with the last
    5 averages for points and salary'''
    merge_df = pd.merge(roto_df, stat_df, on = ['GameID', 'Name', 'Team', 'Date'], how = 'inner')
    player_list = np.array(merge_df.Name.value_counts().index) 
    new_df = pd.DataFrame(columns = merge_df.columns.to_list())
    for player in tqdm(player_list):
        player_df = merge_df[merge_df.Name == player]
        player_df = player_df.sort_values(by = 'Date')
        fdp_avg = []
        fds_avg = []
        risk = []
        for row in range(len(player_df)): 
            if row < num_games: 
                fdp_avg.append(None)
                fds_avg.append(None)
                risk.append(0)
                continue
            last_fds = player_df.iloc[row-num_games:row, :]['FD Sal'].mean()
            last_fdp = player_df.iloc[row-num_games:row, :]['FDP'].mean()
            last_risk = player_df.iloc[row-num_games:row, :]['FDP'].std()
            fdp_avg.append(last_fds)
            fds_avg.append(last_fdp)
            risk.append(last_risk)
        player_df['L_FDP'] = fdp_avg
        player_df['L_FDS'] = fds_avg
        player_df['Risk'] = risk
        new_df = new_df.append(player_df, ignore_index = True)
          
    new_df.to_csv(f'NewData/Merge({season})[{num_games}].csv', index = False)
    return new_df.sort_values(by = ['GameID', 'Team'])

merge_2020 = flast_five(season_2020, roto_2020, '19-20')
merge_2019 = flast_five(season_2019, roto_2019, '18-19')

In [ ]:
print(merge_2020.shape, merge_2019.shape)
merge_2020.head(5)

### Getting Averages for each stat over the last 10 games

In [ ]:
merge_2020_df = pd.read_csv(f'NewData/Merge(19-20)[{num_games}].csv')
merge_2019_df = pd.read_csv(f'NewData/Merge(18-19)[{num_games}].csv')

In [ ]:
def stat_averages(df): 
    '''This Function Will find the averages for each stat for a season'''
    player_list = np.array(df.Name.value_counts().index)
    col = ['MP', 'FG', 'FGA', 'FG%', '3P', '3PA',
                  '3P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK',
                  'TOV', 'PF', 'PTS', '+-']
    add_col = [f'{num_games}_{i}' for i in col]
    print(add_col)
    new_df = pd.DataFrame(columns = df.columns.to_list() + add_col)
    for player in player_list:
        player_df = df[df.Name == player]
        player_df = player_df.sort_values(by = 'Date')
        for c in col: 
            avg = [] 
            for row in range(len(player_df)): 
                if row < num_games: 
                    avg.append(None)
                    continue 
                last = player_df.iloc[row-num_games:row,:][f'{c}'].mean()
                avg.append(last)
            player_df[f'{num_games}_{c}'] = avg
            new_df = new_df.append(player_df,ignore_index = True)
            print(new_df.head(100))
            
        break
        
#         fdp_avg = []
#         fds_avg = []
#         risk = []
#         for row in range(len(player_df)): 
#             if row < num_games: 
#                 fdp_avg.append(None)
#                 fds_avg.append(None)
#                 risk.append(0)
#                 continue
#             last_fds = player_df.iloc[row-num_games:row, :]['FD Sal'].mean()
#             last_fdp = player_df.iloc[row-num_games:row, :]['FDP'].mean()
#             last_risk = player_df.iloc[row-num_games:row, :]['FDP'].std()
#             fdp_avg.append(last_fds)
#             fds_avg.append(last_fdp)
#             risk.append(last_risk)
#         player_df['L_FDP'] = fdp_avg
#         player_df['L_FDS'] = fds_avg
#         player_df['Risk'] = risk
#         new_df = new_df.append(player_df, ignore_index = True)
          
#     new_df.to_csv(f'NewData/Merge({season})[{num_games}].csv', index = False)
#     return new_df.sort_values(by = ['GameID', 'Team'])

stat_averages(merge_2020_df)